create-prefect-storage:
	prefect storage create

create-prefect-deployment:
	prefect deployment create homework.py

prefect-work-queue-preview:
	prefect work-queue preview 5a9f829d-0a85-4e4c-bcfa-4dc7c1d8a3e5

prefect-work-agent-start:
	prefect agent start 5a9f829d-0a85-4e4c-bcfa-4dc7c1d8a3e5